### 1-D Array

In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[3]

3

In [5]:
arr[3: 8]

array([3, 4, 5, 6, 7])

In [6]:
arr[0: 5] = 100

In [11]:
arr

array([99, 99, 99,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr = np.arange(11)

In [12]:
arr_slice = arr[:3]

In [13]:
arr_slice = 99

In [14]:
arr_slice

99

In [15]:
arr

array([99, 99, 99,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
arr_copy = arr.copy()

In [25]:
arr_copy[:5] = 100

In [26]:
arr_copy

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [27]:
arr

array([99, 99, 99,  3,  4,  5,  6,  7,  8,  9, 10])

### 2-D Array

In [31]:
arr_2d = np.arange(1, 10).reshape(3,3)

In [32]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr_2d[1,2]

6

In [34]:
arr_2d[0][1]

2

In [37]:
arr_2d[1:, :2]

array([[4, 5],
       [7, 8]])

### Conditional Selection

In [38]:
arr = np.arange(1, 11)

In [39]:
arr_bool = arr > 5

In [40]:
arr_bool

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [41]:
arr[arr_bool]

array([ 6,  7,  8,  9, 10])

In [42]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [43]:
arr[arr<4]

array([1, 2, 3])

In [44]:
arr[arr%2 == 0]

array([ 2,  4,  6,  8, 10])