In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
np.array([[1, 2, 3], 
                 [4, 5, 6,], 
                 [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.arange(0, 11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones(4)

array([1., 1., 1., 1.])

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.random.rand(5)

array([0.09264413, 0.73668568, 0.49236223, 0.23165478, 0.03585904])

In [14]:
np.random.rand(4,5)

array([[0.09086783, 0.40923287, 0.2595761 , 0.28522205, 0.38491397],
       [0.32378368, 0.2314117 , 0.76617815, 0.99885488, 0.81729121],
       [0.03265451, 0.62261195, 0.60325246, 0.82108036, 0.24143789],
       [0.54730788, 0.53506924, 0.57305347, 0.40457074, 0.33395807]])

In [15]:
np.random.randn(4)

array([ 0.57796191,  0.71022121, -1.36005443,  1.08606041])

In [16]:
np.random.randn(3,4)

array([[-0.82930073, -0.1573677 , -0.33509761, -0.92712542],
       [-2.62160176, -0.35655556,  0.37234618,  1.50706845],
       [ 0.54768169, -0.27364249,  0.19682408, -0.10035169]])

In [18]:
np.random.randint(1, 100, 10)

array([23, 86, 24, 65, 98, 26, 89, 16, 41, 65])

In [19]:
np.random.randint(1, 100, (3,4))

array([[18, 61, 30, 58],
       [50, 79, 29, 11],
       [86, 50, 80, 58]])

In [20]:
arr = np.arange(25)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
rand_arr = np.random.randint(0, 50, 10)

In [23]:
rand_arr

array([ 8, 18, 30, 46, 29, 15, 41, 15, 36, 29])

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
rand_arr.max()

46

In [26]:
rand_arr.min()

8

In [27]:
#return the index number of the max number
rand_arr.argmax()

3

In [28]:
#return the index number of the min number
rand_arr.argmin()

0

In [32]:
arr.reshape(5,5).shape

(5, 5)

In [31]:
rand_arr.shape

(10,)

In [33]:
arr.dtype

dtype('int32')

In [34]:
rand_arr.dtype

dtype('int32')